/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  MasterData: () => import('#controllers/master_data_controller'),
  BlogCategories: () => import('#controllers/blog_categories_controller'),
  Posts: () => import('#controllers/posts_controller'),
  Categories: () => import('#controllers/categories_controller'),
  Products: () => import('#controllers/products_controller'),
}
