/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  Base: () => import('#controllers/base_controller'),
  MasterData: () => import('#controllers/master_data_controller'),
}
