// Generated by scripts/i18n/manifest.ts. Do not edit manually.
import type { Messages } from "@lingui/core";

type CatalogModule = {
	default?: Messages | { messages?: Messages };
	messages?: Messages;
};
export type CatalogLoader = () => Promise<CatalogModule>;
export type CatalogManifest = Record<string, Record<string, CatalogLoader>>;

export const catalogManifest: CatalogManifest = {};
